### PR TITLE
Alphabetical sorting obeys property shorthands

### LINKED ISSUE #50: Alphabetical order exception for overriding shorthand declaration?
When I have `order/properties-alphabetical-order` I get a conflict with the following code:

```css
.foo {
    border-color: red;
    border-bottom-color: yellow;
}
```

If I sort alphabetically, then the bottom border color gets overridden by the shorthand. Is there a way to resolve this?

### PR DESCRIPTION
**Pull request by jamesarosen**
Given
```css
border-color: transparent;
border-bottom-color: pink;
```

the default alphabetical sort would rorder that to
```css
border-bottom-color: pink;
border-color: transparent;
```

That changes the behavior since the shorthand `border-color` now overrides the longhand
`border-bottom-color`. This commit makes the alphabetical sorting shorthand-aware.

This commit also upgrades postcss-sorting to ^5.0.1 so the "fix" logic is the same as the
linting logic.

See https://github.com/hudochenkov/postcss-sorting/pull/85

Closes #50

### CODE REVIEW

**Comment by hudochenkov** [comment]
A loot of tests are failing. https://travis-ci.org/hudochenkov/stylelint-order/jobs/557424260

File: rules/checkAlphabeticalOrder.js [hunk 1]
```diff
@@ -1,6 +1,23 @@
 const postcss = require('postcss');
+const shorthandData = require('./shorthandData');
+
+function isShorthand(a, b) {
+	const longhands = shorthandData[a] || [];
+
+	return longhands.contains(b);
```
Comment (hudochenkov) [inline rules/checkAlphabeticalOrder.js]:
```suggestion
	return longhands.includes(b);
```

**Comment by hudochenkov** [comment]
When you fix, please, don't force push. If you force push, then I can't see what changes you did and I have to review everything again. I'll squash commits on merge for clean Git history.

File: rules/properties-alphabetical-order/README.md [hunk 2]
```diff
@@ -11,6 +11,9 @@ a {
  * These properties */
 ```
 
+Shorthand properties *must always* precede their longhand counterparts, even if that means they are not alphabetized.
+(See also [`declaration-block-no-shorthand-property-overrides`](https://github.com/stylelint/stylelint/tree/master/lib/rules/declaration-block-no-shorthand-property-overrides).)
```
Comment (hudochenkov) [inline rules/properties-alphabetical-order/README.md]:
```suggestion
(See also [`declaration-block-no-shorthand-property-overrides`](https://stylelint.io/user-guide/rules/declaration-block-no-shorthand-property-overrides/).)
```

**Comment by hudochenkov** [comment]
Thank you! Awesome job!
